kind: Application
apiVersion: iofog.org/v3
metadata:
  name: darcy-ai-explorer
spec:
  microservices:
    - name: darcy-ai-explorer
      agent:
        name: ''
      images:
        arm: 'darcyai/darcy-ai-explorer:0.0.6'
        x86: 'darcyai/darcy-ai-explorer:0.0.6'
      container:
        rootHostAccess: true
        ports:
          - external: 5001
            internal: 5000
            public:
              schemes:
                - https
              protocol: http
        volumes:
          - containerDestination: /dev
            hostDestination: /dev
            type: bind
            accessMode: rw
